/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimulateurRouteImport } from './routes/simulateur'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as DiagnosticsIndexRouteImport } from './routes/diagnostics.index'
import { Route as GuidesPrixDiagnosticImmobilierRouteImport } from './routes/guides.prix-diagnostic-immobilier'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as DiagnostiqueurImmobilierVilleRouteImport } from './routes/diagnostiqueur-immobilier.$ville'
import { Route as DiagnosticsSlugRouteImport } from './routes/diagnostics.$slug'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateurRoute = SimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsIndexRoute = DiagnosticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiagnosticsRoute,
} as any)
const GuidesPrixDiagnosticImmobilierRoute =
  GuidesPrixDiagnosticImmobilierRouteImport.update({
    id: '/guides/prix-diagnostic-immobilier',
    path: '/guides/prix-diagnostic-immobilier',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnostiqueurImmobilierVilleRoute =
  DiagnostiqueurImmobilierVilleRouteImport.update({
    id: '/diagnostiqueur-immobilier/$ville',
    path: '/diagnostiqueur-immobilier/$ville',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiagnosticsSlugRoute = DiagnosticsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DiagnosticsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/diagnostics': typeof DiagnosticsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/simulateur': typeof SimulateurRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/zones': typeof ZonesRoute
  '/diagnostics/$slug': typeof DiagnosticsSlugRoute
  '/diagnostiqueur-immobilier/$ville': typeof DiagnostiqueurImmobilierVilleRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/prix-diagnostic-immobilier': typeof GuidesPrixDiagnosticImmobilierRoute
  '/diagnostics/': typeof DiagnosticsIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/simulateur': typeof SimulateurRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/zones': typeof ZonesRoute
  '/diagnostics/$slug': typeof DiagnosticsSlugRoute
  '/diagnostiqueur-immobilier/$ville': typeof DiagnostiqueurImmobilierVilleRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/prix-diagnostic-immobilier': typeof GuidesPrixDiagnosticImmobilierRoute
  '/diagnostics': typeof DiagnosticsIndexRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/diagnostics': typeof DiagnosticsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/simulateur': typeof SimulateurRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/zones': typeof ZonesRoute
  '/diagnostics/$slug': typeof DiagnosticsSlugRoute
  '/diagnostiqueur-immobilier/$ville': typeof DiagnostiqueurImmobilierVilleRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/prix-diagnostic-immobilier': typeof GuidesPrixDiagnosticImmobilierRoute
  '/diagnostics/': typeof DiagnosticsIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/devis'
    | '/diagnostics'
    | '/mentions-legales'
    | '/simulateur'
    | '/sitemap.xml'
    | '/tarifs'
    | '/zones'
    | '/diagnostics/$slug'
    | '/diagnostiqueur-immobilier/$ville'
    | '/guides/$slug'
    | '/guides/prix-diagnostic-immobilier'
    | '/diagnostics/'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/devis'
    | '/mentions-legales'
    | '/simulateur'
    | '/sitemap.xml'
    | '/tarifs'
    | '/zones'
    | '/diagnostics/$slug'
    | '/diagnostiqueur-immobilier/$ville'
    | '/guides/$slug'
    | '/guides/prix-diagnostic-immobilier'
    | '/diagnostics'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/devis'
    | '/diagnostics'
    | '/mentions-legales'
    | '/simulateur'
    | '/sitemap.xml'
    | '/tarifs'
    | '/zones'
    | '/diagnostics/$slug'
    | '/diagnostiqueur-immobilier/$ville'
    | '/guides/$slug'
    | '/guides/prix-diagnostic-immobilier'
    | '/diagnostics/'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  DevisRoute: typeof DevisRoute
  DiagnosticsRoute: typeof DiagnosticsRouteWithChildren
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  SimulateurRoute: typeof SimulateurRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  ZonesRoute: typeof ZonesRoute
  DiagnostiqueurImmobilierVilleRoute: typeof DiagnostiqueurImmobilierVilleRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesPrixDiagnosticImmobilierRoute: typeof GuidesPrixDiagnosticImmobilierRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulateur': {
      id: '/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof SimulateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics/': {
      id: '/diagnostics/'
      path: '/'
      fullPath: '/diagnostics/'
      preLoaderRoute: typeof DiagnosticsIndexRouteImport
      parentRoute: typeof DiagnosticsRoute
    }
    '/guides/prix-diagnostic-immobilier': {
      id: '/guides/prix-diagnostic-immobilier'
      path: '/guides/prix-diagnostic-immobilier'
      fullPath: '/guides/prix-diagnostic-immobilier'
      preLoaderRoute: typeof GuidesPrixDiagnosticImmobilierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostiqueur-immobilier/$ville': {
      id: '/diagnostiqueur-immobilier/$ville'
      path: '/diagnostiqueur-immobilier/$ville'
      fullPath: '/diagnostiqueur-immobilier/$ville'
      preLoaderRoute: typeof DiagnostiqueurImmobilierVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics/$slug': {
      id: '/diagnostics/$slug'
      path: '/$slug'
      fullPath: '/diagnostics/$slug'
      preLoaderRoute: typeof DiagnosticsSlugRouteImport
      parentRoute: typeof DiagnosticsRoute
    }
  }
}

interface DiagnosticsRouteChildren {
  DiagnosticsSlugRoute: typeof DiagnosticsSlugRoute
  DiagnosticsIndexRoute: typeof DiagnosticsIndexRoute
}

const DiagnosticsRouteChildren: DiagnosticsRouteChildren = {
  DiagnosticsSlugRoute: DiagnosticsSlugRoute,
  DiagnosticsIndexRoute: DiagnosticsIndexRoute,
}

const DiagnosticsRouteWithChildren = DiagnosticsRoute._addFileChildren(
  DiagnosticsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  DevisRoute: DevisRoute,
  DiagnosticsRoute: DiagnosticsRouteWithChildren,
  MentionsLegalesRoute: MentionsLegalesRoute,
  SimulateurRoute: SimulateurRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  ZonesRoute: ZonesRoute,
  DiagnostiqueurImmobilierVilleRoute: DiagnostiqueurImmobilierVilleRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesPrixDiagnosticImmobilierRoute: GuidesPrixDiagnosticImmobilierRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
